---
label: Services
hide_body: true
display_field: heading
fields:
- type: text
  name: a_title
  label: Title
  description: 
- type: text
  name: a_subtitle
  label: Subtitle 1
  description: 
- type: text
  name: b_subtitle
  label: Subtitle 2
  description: 
- type: text
  name: a_1
  label: Service A
  description: 
- type: textarea
  name: a_2
  label: Service A Description
  description: 
- type: text
  name: b_1
  label: Service B
  description: 
- type: textarea
  name: b_2
  label: Service B Description
  description: 
- type: text
  name: c_1
  label: Service C
  description: 
- type: textarea
  name: c_2
  label: Service C Description
  description: 
- type: text
  name: d_1
  label: Service D
  description: 
- type: textarea
  name: d_2
  label: Service D Description
  description: 
- type: text
  name: e_1
  label: Service E
  description: 
- type: textarea
  name: e_2
  label: Service E Description
  description: 
- type: text
  name: f_1
  label: Service F
  description: 
- type: textarea
  name: f_2
  label: Service F Description
  description: 
- type: text
  name: g_1
  label: Service G
  description: 
- type: textarea
  name: g_2
  label: Service G Description
  description: 
- type: text
  name: h_1
  label: Service H
  description: 
- type: textarea
  name: h_2
  label: Service H Description
  description: 
- type: text
  name: i_1
  label: Service I
  description: 
- type: textarea
  name: i_2
  label: Service I Description
  description: 
- type: text
  name: j_1
  label: Service J
  description: 
- type: textarea
  name: j_2
  label: Service J Description
  description: 
- type: text
  name: k_1
  label: Service K
  description: 
- type: textarea
  name: k_2
  label: Service K Description
  description: 
- type: text
  name: l_1
  label: Service L
  description: 
- type: textarea
  name: l_2
  label: Service L Description
  description: 
- type: text
  name: m_1
  label: Service M
  description: 
- type: textarea
  name: m_2
  label: Service M Description
  description: 
